server:
  port: 9090

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: true
  jpa:
    database: h2
    hibernate:
      ddl-auto: create
    show-sql: true

application.message: Hello demo

